name: GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install packages
        run: npm ci && npm i -g surge

      - name: Build
        run: npm run build

      - name: Publish
        run: surge ./out dev-gem.azuro.org --token ${{ secrets.SURGE_TOKEN }}
